#!/usr/bin/env python3
"""Clean old local media artifacts generated by the Feishu pipeline."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


SECONDS_PER_DAY = 24 * 60 * 60


@dataclass
class CleanupResult:
    candidate_count: int = 0
    candidate_bytes: int = 0
    deleted_count: int = 0
    deleted_bytes: int = 0
    skipped_count: int = 0
    errors: list[str] | None = None

    def __post_init__(self):
        if self.errors is None:
            self.errors = []


def repo_root_from_script() -> Path:
    return Path(__file__).resolve().parents[1]


def default_log_file(repo_root: Path) -> Path:
    return repo_root / "tk_toolkit_dual" / "cleanup_generated_files.log"


def human_bytes(size: int) -> str:
    value = float(size)
    for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
        if value < 1024 or unit == "TiB":
            if unit == "B":
                return f"{int(value)} {unit}"
            return f"{value:.1f} {unit}"
        value /= 1024
    return f"{size} B"


def resolve_under_repo(repo_root: Path, path: Path) -> Path | None:
    try:
        resolved = path.resolve(strict=False)
        resolved.relative_to(repo_root)
        return resolved
    except ValueError:
        return None


def discover_whitelist_roots(repo_root: Path) -> list[Path]:
    roots: list[Path] = []

    workspace_ryan = repo_root / "tk_toolkit_dual" / "workspace_ryan"
    if workspace_ryan.is_dir():
        roots.extend(
            path
            for path in sorted(workspace_ryan.iterdir())
            if path.is_dir() and path.name.endswith("_work")
        )

    for name in ("first_last_video_work", "multi_role_first_last_work"):
        path = repo_root / name
        if path.is_dir():
            roots.append(path)

    safe_roots: list[Path] = []
    seen: set[Path] = set()
    for root in roots:
        resolved = resolve_under_repo(repo_root, root)
        if resolved and resolved not in seen:
            safe_roots.append(resolved)
            seen.add(resolved)
    return safe_roots


def load_tracked_paths(repo_root: Path) -> set[Path]:
    try:
        completed = subprocess.run(
            ["git", "ls-files", "-z"],
            cwd=repo_root,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except (OSError, subprocess.CalledProcessError):
        return set()

    tracked: set[Path] = set()
    for raw in completed.stdout.split(b"\0"):
        if raw:
            tracked.add((repo_root / raw.decode("utf-8", errors="surrogateescape")).resolve(strict=False))
    return tracked


def is_within_roots(path: Path, roots: Iterable[Path]) -> bool:
    for root in roots:
        try:
            path.relative_to(root)
            return True
        except ValueError:
            continue
    return False


def iter_cleanup_candidates(
    roots: Iterable[Path],
    *,
    cutoff: float,
    tracked_paths: set[Path],
) -> Iterable[Path]:
    root_list = list(roots)
    for root in root_list:
        if not root.is_dir():
            continue
        for dirpath, dirnames, filenames in os.walk(root):
            current_dir = Path(dirpath)
            if current_dir.is_symlink():
                dirnames[:] = []
                continue
            for filename in filenames:
                path = current_dir / filename
                if path.is_symlink():
                    continue
                if not path.is_file():
                    continue
                resolved = path.resolve(strict=False)
                if resolved in tracked_paths:
                    continue
                if not is_within_roots(resolved, root_list):
                    continue
                try:
                    if path.stat().st_mtime < cutoff:
                        yield path
                except OSError:
                    continue


def remove_empty_child_dirs(roots: Iterable[Path]) -> int:
    removed = 0
    for root in roots:
        if not root.is_dir():
            continue
        for dirpath, dirnames, _filenames in os.walk(root, topdown=False):
            path = Path(dirpath)
            if path == root or path.is_symlink():
                continue
            try:
                path.rmdir()
                removed += 1
            except OSError:
                pass
    return removed


def log_line(message: str, log_file: Path | None) -> None:
    print(message)
    if log_file is None:
        return
    log_file.parent.mkdir(parents=True, exist_ok=True)
    with log_file.open("a", encoding="utf-8") as handle:
        handle.write(message + "\n")


def run_cleanup(
    *,
    repo_root: Path | str,
    days: int,
    execute: bool,
    now: float | None = None,
    log_file: Path | str | None = None,
    tracked_paths: set[Path] | None = None,
) -> CleanupResult:
    repo_root = Path(repo_root).resolve(strict=False)
    log_path = Path(log_file).resolve(strict=False) if log_file else None
    current_time = time.time() if now is None else now
    cutoff = current_time - days * SECONDS_PER_DAY
    roots = discover_whitelist_roots(repo_root)
    tracked = set() if tracked_paths is None else {Path(path).resolve(strict=False) for path in tracked_paths}

    candidates = list(iter_cleanup_candidates(roots, cutoff=cutoff, tracked_paths=tracked))
    result = CleanupResult()
    result.candidate_count = len(candidates)

    for path in candidates:
        try:
            result.candidate_bytes += path.stat().st_size
        except OSError:
            result.skipped_count += 1

    mode = "execute" if execute else "dry-run"
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S %z", time.localtime(current_time))
    log_line(
        f"[{timestamp}] cleanup_generated_files mode={mode} days={days} "
        f"roots={len(roots)} candidates={result.candidate_count} "
        f"candidate_size={human_bytes(result.candidate_bytes)}",
        log_path,
    )

    if not execute:
        for path in candidates[:200]:
            log_line(f"DRY-RUN {path}", log_path)
        if len(candidates) > 200:
            log_line(f"DRY-RUN ... {len(candidates) - 200} more files omitted", log_path)
        return result

    for path in candidates:
        try:
            size = path.stat().st_size
            path.unlink()
            result.deleted_count += 1
            result.deleted_bytes += size
            log_line(f"DELETED {path}", log_path)
        except OSError as exc:
            result.skipped_count += 1
            result.errors.append(f"{path}: {exc}")
            log_line(f"ERROR {path}: {exc}", log_path)

    removed_dirs = remove_empty_child_dirs(roots)
    log_line(
        f"SUMMARY deleted={result.deleted_count} "
        f"freed={human_bytes(result.deleted_bytes)} skipped={result.skipped_count} "
        f"empty_dirs_removed={removed_dirs}",
        log_path,
    )
    return result


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Clean old Feishu pipeline generated local files.")
    parser.add_argument("--days", type=int, default=7, help="Delete files older than this many days.")
    parser.add_argument("--execute", action="store_true", help="Actually delete files. Defaults to dry-run.")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=repo_root_from_script(),
        help="Workspace repository root.",
    )
    parser.add_argument(
        "--log-file",
        type=Path,
        default=None,
        help="Optional log file path. Defaults to tk_toolkit_dual/cleanup_generated_files.log.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    if args.days < 1:
        print("--days must be >= 1", file=sys.stderr)
        return 2

    repo_root = args.repo_root.resolve(strict=False)
    log_file = args.log_file if args.log_file is not None else default_log_file(repo_root)
    result = run_cleanup(
        repo_root=repo_root,
        days=args.days,
        execute=args.execute,
        log_file=log_file,
        tracked_paths=load_tracked_paths(repo_root),
    )
    return 1 if result.errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
